# Generated by Django 5.1 on 2024-08-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0002_service_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='example_image',
            field=models.ImageField(blank=True, upload_to='service'),
        ),
    ]
