# Generated by Django 5.1 on 2024-08-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0006_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='mini_description',
            field=models.TextField(blank=True),
        ),
    ]
