# Generated by Django 5.1 on 2024-08-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0007_project_mini_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url_title',
            field=models.SlugField(blank=True),
        ),
    ]
