# Generated by Django 5.1 on 2024-08-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0009_project_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='example_image',
            field=models.ImageField(blank=True, upload_to='service'),
        ),
        migrations.AlterField(
            model_name='project',
            name='banner',
            field=models.ImageField(blank=True, upload_to='project'),
        ),
    ]
