# Generated by Django 5.1 on 2024-08-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0010_project_example_image_alter_project_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='service',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
