# Generated by Django 5.1 on 2024-08-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0011_project_client_project_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
